import { useEffect, useState } from 'react'
import { Video, ExternalLink } from 'lucide-react'
import { useT } from '../lib/i18n'
import { useAuth } from '../lib/auth'
import { supabase } from '../lib/supabase'
import { PageHeader } from '../components/ui'

const lessons = [
 ['presentation','Avant signature','Before signing','Arqely en 2 minutes','Arqely in 2 minutes','2 min','Présenter les clients accompagnés, les six services et les étapes de collaboration. Montrer des réalisations réelles. Terminer par une invitation à discuter du besoin.','Introduce the customers we help, our six services and the project stages. Show actual work. Invite the viewer to discuss their needs.',true],
 ['testimonial','Avant signature','Before signing','Le projet de Nolan','Nolan’s project','60–90 s','Questions : pourquoi ce site ? Quelles hésitations au départ ? Comment la collaboration s’est-elle passée ? Quel bénéfice concret ? À qui recommander Arqely ? Alterner ses mots avec des images du site. Faire approuver le montage et les usages. À la livraison, parler de l’expérience ; ajouter les résultats uniquement lorsqu’ils sont mesurés.','Ask: why this website? Initial concerns? How was the collaboration? What concrete benefit? Who would you recommend Arqely to? Combine his own words with website footage. Obtain approval for the edit and intended uses. At delivery, discuss the experience; add results only when measured.',true],
 ['welcome','Après signature','After signing','Bienvenue chez Arqely','Welcome to Arqely','2–3 min','Présenter l’interlocuteur, qui fait quoi, les étapes et le canal de communication. Reprendre le calendrier convenu au devis, sans promettre un délai universel. Action : confirmer le rendez-vous de démarrage.','Introduce the contact person, responsibilities, stages and communication channel. Use the schedule agreed in the quote, without promising a universal turnaround. Action: confirm the kickoff meeting.',true],
 ['prepare','Démarrage','Kickoff','Préparer votre projet','Prepare your project','3–5 min','Checklist : logo, textes, photos autorisées, coordonnées, exemples appréciés, objectifs et accès nécessaires. Montrer où déposer les contenus. Transmettre les accès par un canal sécurisé, jamais dans une vidéo. Action : compléter le brief et transmettre les éléments.','Checklist: logo, copy, approved photos, contact details, references, goals and required access. Show where to submit content. Share credentials securely, never in a video. Action: complete the brief and provide the materials.',true],
 ['feedback','Validation','Review','Faire vos retours','Give feedback','2–3 min','Montrer comment commenter une page et regrouper les retours. Expliquer les séries de corrections prévues au devis. Une nouvelle fonctionnalité reçoit un supplément fixe accepté avant réalisation. Action : envoyer une liste consolidée puis valider par écrit.','Show how to comment on a page and consolidate feedback. Explain the revision rounds in the quote. A new feature requires an agreed fixed supplement before work. Action: send one consolidated list, then approve in writing.',false],
 ['handover','Livraison','Handover','Utiliser votre site','Use your website','3–5 min','Enregistrer une démonstration adaptée au site du client : connexion, modification courante, formulaire et demande d’aide. Masquer les données personnelles et secrets. Joindre un résumé écrit. Action : effectuer une première modification accompagnée.','Record a client-specific demonstration: sign in, common edits, form and support requests. Hide personal data and secrets. Attach a written summary. Action: perform a first guided edit.',false],
 ['support','Suivi mensuel','Monthly support','Votre accompagnement','Your ongoing support','2–3 min','Expliquer les prestations réellement souscrites, les limites, les délais convenus et comment demander une modification. Distinguer maintenance et nouveaux développements. Action : retrouver le canal de support et planifier le bilan à 30 jours.','Explain the services actually purchased, limits, agreed response times and how to request an update. Distinguish maintenance from new development. Action: locate the support channel and schedule a 30-day review.',false],
] as const
const statuses = ['planned','recording','review','ready'] as const
type Entry = {status: typeof statuses[number]; url: string; notes: string}
const empty: Entry = {status:'planned',url:'',notes:''}
function valid(v: unknown): v is Entry { if(!v || typeof v!=='object') return false; const e=v as Entry; return statuses.includes(e.status)&&typeof e.url==='string'&&typeof e.notes==='string'&&safeUrl(e.url) }
function safeUrl(url: string) { if(!url)return true;try{const u=new URL(url);return u.protocol==='https:'&&!u.username&&!u.password}catch{return false} }
export default function ClientVideos(){
 const {locale}=useT();const {profile}=useAuth();const c=(fr:string,en:string)=>locale==='fr'?fr:en
 const [entries,setEntries]=useState<Record<string,Entry>>({});const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [message,setMessage]=useState('');const [editing,setEditing]=useState<string|null>(null);const [draft,setDraft]=useState<Entry>(empty);const [busy,setBusy]=useState(false)
 useEffect(()=>{let active=true;(async()=>{try{const {data,error}=await supabase.from('app_settings').select('key,value').in('key',lessons.map(l=>'client_video_v1_'+l[0]));if(error)throw error;const result:Record<string,Entry>={};for(const row of data??[]){const v=JSON.parse(row.value);if(!valid(v))throw new Error(c('Une fiche vidéo enregistrée est invalide.','A saved video entry is invalid.'));result[row.key.replace('client_video_v1_','')]=v}if(active)setEntries(result)}catch{if(active)setError(c('Chargement impossible. Les plans restent consultables ; rechargez la page avant de modifier les liens.','Unable to load. Plans remain available; reload before editing links.'))}finally{if(active)setLoading(false)}})();return()=>{active=false}},[])
 async function save(id:string){if(busy)return;if(!valid(draft)||(draft.status==='ready'&&!draft.url)){setMessage(c('Saisissez un lien HTTPS valide. Une vidéo prête doit avoir un lien.','Enter a valid HTTPS link. A ready video needs a link.'));return}setBusy(true);try{const {error}=await supabase.from('app_settings').upsert({key:'client_video_v1_'+id,value:JSON.stringify(draft)}).select('key').single();if(error)throw error;setEntries(v=>({...v,[id]:{...draft}}));setEditing(null);setMessage(c('Fiche enregistrée pour l’équipe.','Entry saved for the team.'))}catch{setMessage(c('Enregistrement impossible. Vos modifications restent dans le formulaire.','Unable to save. Your changes remain in the form.'))}finally{setBusy(false)}}
 const label=(s:Entry['status'])=>({planned:c('À préparer','To prepare'),recording:c('À tourner','To record'),review:c('À valider','To review'),ready:c('Prête','Ready')})[s]
 return <div><PageHeader title={c('Vidéos clients','Client videos')}/><section className="card p-7 mb-6 bg-neutral-900 text-white"><Video size={28}/><h2 className="text-3xl mt-5 mb-3">{c('Rassurer. Guider. Accompagner.','Reassure. Guide. Support.')}</h2><p className="text-sm text-neutral-300 max-w-2xl">{c('7 vidéos à préparer pour le parcours client. Commencez par les 4 priorités, puis complétez la bibliothèque au fil des projets.','7 videos to prepare for the client journey. Start with the 4 priorities, then expand the library through your projects.')}</p><p className="text-xs text-neutral-400 mt-4">{c('Espace interne à l’équipe. Aucun envoi automatique aux clients. Les vidéos ne sont pas encore tournées par défaut.','Internal team workspace. Nothing is sent to clients automatically. Videos are not recorded by default.')}</p></section>
 {loading&&<p role="status">{c('Chargement des liens…','Loading links…')}</p>}{error&&<p role="alert" className="card p-4 mb-4">{error}</p>}{message&&<p role="status" className="mb-4">{message}</p>}
 <div className="grid lg:grid-cols-2 gap-5">{lessons.map((l,i)=>{const e=entries[l[0]]??empty;return <article className="card p-6" key={l[0]}><div className="flex flex-wrap justify-between gap-2 text-xs text-neutral-500"><span>0{i+1} · {c(l[1],l[2])} · {l[5]}</span><span>{loading||error?c('Statut non vérifié','Status unverified'):label(e.status)}</span></div><h2 className="text-xl font-semibold mt-4">{c(l[3],l[4])}</h2>{l[8]&&<p className="text-xs mt-2 font-medium">{c('À produire en priorité','Produce first')}</p>}<p className="text-sm text-neutral-600 leading-relaxed mt-4">{c(l[6],l[7])}</p>{e.notes&&<p className="text-sm whitespace-pre-wrap border-t mt-4 pt-4">{e.notes}</p>}
 <div className="flex flex-wrap gap-3 mt-5">{e.url&&<a className="btn-secondary" href={e.url} target="_blank" rel="noopener noreferrer">{c('Ouvrir la vidéo','Open video')}<ExternalLink size={14}/></a>}{profile?.role==='owner'&&!loading&&!error&&<button className="btn-secondary" disabled={busy} onClick={()=>{setEditing(l[0]);setDraft({...e});setMessage('')}}>{c('Gérer la vidéo','Manage video')}</button>}</div>
 {editing===l[0]&&<form className="space-y-3 mt-4 border-t pt-4" onSubmit={ev=>{ev.preventDefault();save(l[0])}}><label className="block text-sm">{c('Statut','Status')}<select className="input" value={draft.status} onChange={ev=>setDraft({...draft,status:ev.target.value as Entry['status']})}>{statuses.map(s=><option key={s} value={s}>{label(s)}</option>)}</select></label><label className="block text-sm">{c('Lien de la vidéo (HTTPS)','Video link (HTTPS)')}<input className="input" type="url" value={draft.url} onChange={ev=>setDraft({...draft,url:ev.target.value.trim()})}/></label><label className="block text-sm">{c('Notes de production / résumé / prochaine action','Production notes / summary / next action')}<textarea className="input" rows={4} value={draft.notes} onChange={ev=>setDraft({...draft,notes:ev.target.value})}/></label><p className="text-xs text-neutral-500">{c('Vérifiez les accès du lien et l’accord des personnes filmées avant diffusion. Ce lien ne donne pas accès au CRM.','Check link permissions and participant approval before sharing. This link does not grant CRM access.')}</p><div className="flex gap-3"><button className="btn-primary" disabled={busy}>{busy?c('Enregistrement…','Saving…'):c('Enregistrer','Save')}</button><button type="button" className="btn-secondary" disabled={busy} onClick={()=>setEditing(null)}>{c('Annuler','Cancel')}</button></div></form>}</article>})}</div></div>
}
