import OfferPackages from '../components/OfferPackages'
import OfferPolicy from '../components/OfferPolicy'
import { useEffect, useState } from 'react'
import { useAuth } from '../lib/auth'
import { useT } from '../lib/i18n'
import { supabase } from '../lib/supabase'
import { defaultOffers, offerFields, validOffer, type Offer, type OfferCopy } from '../lib/offers'
import { PageHeader, Modal } from '../components/ui'
const labels = { objective: ['Objectif client','Client objective'], deliverables: ['Livrables initiaux','Initial deliverables'], scope: ['Périmètre du forfait proposé','Proposed fixed scope'], monthly: ['Accompagnement mensuel','Monthly service'], excluded: ['Hors forfait et frais tiers','Exclusions and third-party costs'], client: ['Éléments à fournir par le client','Client inputs'], acceptance: ['Validation et livraison','Acceptance and delivery'], metrics: ['Indicateurs de suivi','Success measures'] }
export default function Offers() {
 const { locale } = useT(); const { profile } = useAuth(); const copy=(fr:string,en:string)=>locale==='fr'?fr:en
 const [offers,setOffers]=useState(defaultOffers); const [loading,setLoading]=useState(true); const [error,setError]=useState(''); const [saved,setSaved]=useState(''); const [query,setQuery]=useState(''); const [editing,setEditing]=useState<Offer|null>(null); const [busy,setBusy]=useState(false); const [formError,setFormError]=useState('')
 const load=async()=>{setLoading(true);setError('');try {
   const {data,error}=await supabase.from('app_settings').select('key,value').in('key',defaultOffers.map(o=>'offer_v1_'+o.id))
   if(error) throw error
   const next=defaultOffers.map(o=>{const row=data?.find(r=>r.key==='offer_v1_'+o.id);if(!row)return o;const parsed=JSON.parse(row.value);if(!validOffer(parsed,o.id))throw new Error(copy('Une fiche enregistrée est invalide.','A saved offer is invalid.'));return parsed})
   setOffers(next)
 }catch(e){setError(e instanceof Error ? e.message : copy('Chargement du catalogue impossible.','Unable to load catalogue.'))}finally{setLoading(false)}}
 useEffect(()=>{load()},[])
 const save=async()=>{if(!editing||busy)return;if(!validOffer(editing,editing.id)){setFormError(copy('Complétez tous les textes et saisissez des prix positifs ou laissez-les vides.','Complete all text fields and enter non-negative prices or leave them blank.'));return}setBusy(true);setFormError('');try{const {error}=await supabase.from('app_settings').upsert({key:'offer_v1_'+editing.id,value:JSON.stringify(editing)}).select('key').single();if(error)throw error;setOffers(rows=>rows.map(o=>o.id===editing.id?editing:o));setEditing(null);setSaved(copy('Offre enregistrée pour toute l’équipe.','Offer saved for the whole team.'))}catch(e){setFormError(e instanceof Error?e.message:copy('Enregistrement impossible.','Unable to save.'))}finally{setBusy(false)}}
 const price=(v:number|null)=>v===null?copy('À définir','To be defined'):new Intl.NumberFormat(locale === 'fr' ? 'fr-BE' : 'en-GB', {style:'currency',currency:'EUR',minimumFractionDigits:Number.isInteger(v)?0:2,maximumFractionDigits:2}).format(v)
 const visible=offers.filter(o=>Object.values(o[locale]).join(' ').toLocaleLowerCase(locale).includes(query.toLocaleLowerCase(locale)))
 const updateText=(field:keyof OfferCopy,text:string)=>setEditing(o=>o?{...o,[locale]:{...o[locale],[field]:text}}:o)
 return <div><PageHeader title={copy('Nos offres','Our offers')}><button className="btn-secondary" disabled={loading} onClick={load}>{copy('Actualiser','Refresh')}</button></PageHeader>
 <OfferPackages /><div id="individual-offers" className="mb-7 max-w-3xl scroll-mt-6"><p className="font-medium">{copy('6 offres · Création, acquisition et automatisation','6 offers · Creation, acquisition and automation')}</p><p className="text-sm text-neutral-500 mt-2">{copy('Forfaits standards : le périmètre est confirmé avant signature ; un projet plus complexe reçoit un prix fixe adapté. Installation et abonnement sont séparés ; budgets publicitaires et frais tiers sont précisés dans chaque fiche.','Standard packages: scope is confirmed before signing; more complex projects receive an adjusted fixed quote. Setup and subscription are separate; advertising spend and third-party costs are stated in each offer.')}</p><p className="text-xs text-neutral-500 mt-2">{copy('Ces fiches détaillées ne modifient pas les tarifs ni les abonnements déjà enregistrés dans le catalogue de facturation.','These detailed offers do not change existing billing catalogue prices or subscriptions.')}</p></div>
 <OfferPolicy />
 {saved&&<p role="status" className="mb-4">{saved}</p>}
 {error&&<div role="alert" className="card p-4 mb-4">{error}<p>{copy('Les fiches proposées ci-dessous ne reflètent peut-être pas les dernières modifications. Édition désactivée : actualisez pour réessayer.','Proposed offers below may not reflect recent changes. Editing disabled: refresh to retry.')}</p></div>}
 <input className="input mb-5" type="search" aria-label={copy('Rechercher une offre','Search offers')} placeholder={copy('Rechercher une offre, un livrable…','Search an offer or deliverable…')} value={query} onChange={e=>setQuery(e.target.value)}/>
 {loading?<p role="status">{copy('Chargement…','Loading…')}</p>:<div className="grid lg:grid-cols-2 2xl:grid-cols-3 gap-5">{visible.map(o=><article className="card offer-card" key={o.id}><div className="flex items-start justify-between gap-3"><h2 className="text-xl font-semibold">{o[locale].title}</h2>{profile?.role==='owner'&&!error&&<button className="btn-secondary text-xs" onClick={()=>{setFormError('');setSaved('');setEditing(structuredClone(o))}}>{copy('Modifier','Edit')}</button>}</div><p className="text-sm text-neutral-500 mt-3">{o[locale].objective}</p>{JSON.stringify(o)!==JSON.stringify(defaultOffers.find(d=>d.id===o.id))&&<p className="text-xs text-neutral-500 mt-2">{copy('Fiche personnalisée enregistrée. Standard actuel : ' ,'Saved custom offer. Current standard: ')}{price(defaultOffers.find(d=>d.id===o.id)!.initialPrice)} + {price(defaultOffers.find(d=>d.id===o.id)!.monthlyPrice)}{copy('/mois HTVA','/month excl. VAT')}</p>}<div className="grid grid-cols-2 gap-3 my-4"><div className="border-l-2 border-neutral-200 pl-3 py-1"><div className="text-xs">{copy('Prestation initiale HTVA','Initial service excl. VAT')}</div><strong>{price(o.initialPrice)}</strong></div><div className="border-l-2 border-neutral-200 pl-3 py-1"><div className="text-xs">{copy('Mensuel HTVA','Monthly excl. VAT')}</div><strong>{price(o.monthlyPrice)}</strong></div></div><details><summary className="cursor-pointer text-sm font-medium py-2">{copy('Voir la fiche détaillée','View detailed offer')}</summary><div className="space-y-4 pt-3">{offerFields.filter(f=>f!=='objective').map(f=><section key={f}><h3 className="text-sm font-semibold">{labels[f][locale==='fr'?0:1]}</h3><p className="text-sm text-neutral-600 mt-1 whitespace-pre-line">{o[locale][f]}</p></section>)}</div></details></article>)}</div>}
 {!loading&&!visible.length&&<p>{copy('Aucune offre pour cette recherche.','No offers match this search.')}</p>}
 <Modal wide open={editing!==null} onClose={()=>{if(!busy)setEditing(null)}} title={copy('Modifier l’offre — français','Edit offer — English')}>
 {editing&&<form className="space-y-4" onSubmit={e=>{e.preventDefault();save()}}><p className="text-xs text-neutral-500">{copy('Vous modifiez les textes français ; passez le CRM en anglais pour modifier leur traduction. Les prix sont communs aux deux langues.','You are editing English copy; switch CRM language to French to edit French text. Prices are shared.')}</p><label className="block text-sm">{copy('Nom','Name')}<input required className="input" value={editing[locale].title} onChange={e=>updateText('title',e.target.value)}/></label><div className="grid sm:grid-cols-2 gap-3">{(['initialPrice','monthlyPrice'] as const).map(k=><label key={k} className="text-sm">{k==='initialPrice'?copy('Prix initial HTVA (€)','Initial price excl. VAT (€)'):copy('Prix mensuel HTVA (€)','Monthly price excl. VAT (€)')}<input type="number" min="0" step="0.01" className="input" placeholder={copy('À définir','To be defined')} value={editing[k]??''} onChange={e=>setEditing({...editing,[k]:e.target.value===''?null:Number(e.target.value)})}/></label>)}</div>{offerFields.map(f=><label className="block text-sm" key={f}>{labels[f][locale==='fr'?0:1]}<textarea required rows={4} className="input mt-1" value={editing[locale][f]} onChange={e=>updateText(f,e.target.value)}/></label>)}{formError&&<p role="alert">{formError}</p>}<button disabled={busy} className="btn-primary">{busy?copy('Enregistrement…','Saving…'):copy('Enregistrer','Save')}</button></form>}
 </Modal></div>
}
