import { useState } from 'react'
import { Link } from 'react-router-dom'
import { useT, fmtDate } from '../lib/i18n'
import { OwnerName } from './ui'
import { buildActions, type ActionCategory } from '../lib/actionOverview'
import type { Task, Deal, Contact, Subscription } from '../lib/types'
export default function ActionOverview({ tasks, deals, contacts, subscriptions, loading, failed, owner, onEdit }: { tasks: Task[]; deals: Deal[]; contacts: Contact[]; subscriptions: Subscription[]; loading: boolean; failed: boolean; owner?: string; onEdit: (task: Partial<Task>) => void }) {
  const { locale } = useT(); const copy = (fr: string,en: string) => locale === 'fr' ? fr : en
  const [category,setCategory] = useState<'all' | ActionCategory>('all'); const [search,setSearch] = useState('')
  const all = buildActions(tasks,deals,contacts,subscriptions,locale).filter(x => !owner || x.owner === owner)
  const categories = [{ id: 'all', name: copy('Tous les points', 'All items') }, { id: 'tasks', name: copy('Missions', 'Tasks') }, { id: 'deals', name: copy('Affaires sans suivi', 'Deals without follow-up') }, { id: 'contacts', name: copy('Contacts à traiter', 'Contacts to review') }, { id: 'projects', name: copy('Projets & échéances', 'Projects & deadlines') }] as const
  const visible = all.filter(x => (category === 'all' || x.category === category) && `${x.title} ${x.detail}`.toLocaleLowerCase(locale).includes(search.trim().toLocaleLowerCase(locale)))
  return <section className="card overview-panel" aria-label={copy('Vue globale du reste à faire', 'Complete outstanding work overview')}>
    <div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-lg font-semibold tracking-tight">{copy('À faire, en un coup d’œil', 'Your next steps')}</h2><details className="text-xs text-neutral-500 mt-2 max-w-xl"><summary className="cursor-pointer">{copy('Missions, suivi commercial et échéances', 'Tasks, follow-ups and deadlines')}</summary><p className="mt-3 leading-relaxed">{copy('Missions ouvertes, affaires sans tâche liée, contacts à compléter et échéances à 30 jours (retards inclus). Les alertes sont calculées sur les données enregistrées ; plusieurs points peuvent concerner le même client.', 'Open tasks, deals without linked tasks, contacts to complete and deadlines within 30 days (including overdue). Alerts use recorded data; several items may concern the same client.')}</p></details></div><span className="text-4xl font-medium tracking-tight tabular-nums">{loading || failed ? '—' : all.length}</span></div>
    {failed ? <p role="status" className="mt-4 text-sm">{copy('Vue incomplète : corrigez l’erreur de chargement puis actualisez.', 'Incomplete overview: resolve the loading error, then refresh.')}</p> : loading ? <p role="status" className="mt-4">{copy('Chargement…', 'Loading…')}</p> : <>
      <div className="filter-tabs">{categories.map(c => <button key={c.id} aria-pressed={category === c.id} onClick={() => setCategory(c.id)} className="filter-tab">{c.name} · {c.id === 'all' ? all.length : all.filter(x => x.category === c.id).length}</button>)}</div>
      <input className="input mb-3" type="search" aria-label={copy('Rechercher dans tous les points', 'Search all action items')} placeholder={copy('Rechercher dans tout le reste à faire…', 'Search all outstanding work…')} value={search} onChange={e => setSearch(e.target.value)} />
      <div className="max-h-[560px] overflow-y-auto">{visible.map(x => <div key={x.id} className="action-row"><div className="min-w-0 flex-1"><div className="text-[10px] uppercase tracking-wide text-neutral-500 mb-1">{categories.find(c => c.id === x.category)?.name}</div><Link to={x.href} className="text-sm font-medium hover:underline break-words">{x.title}</Link><p className="text-xs text-neutral-500 mt-1 whitespace-pre-line">{x.detail}</p><div className="text-xs mt-1"><OwnerName id={x.owner} /> · {x.due ? fmtDate(x.due,locale,true) : copy('À planifier / vérifier', 'To schedule / review')}</div></div>{x.task ? <button className="btn-secondary text-xs" onClick={() => onEdit(x.task!)}>{copy('Ouvrir la mission', 'Open task')}</button> : x.draft ? <button className="btn-secondary text-xs" onClick={() => onEdit(x.draft!)}>{copy('Planifier', 'Schedule')}</button> : <Link className="btn-secondary text-xs" to={x.href}>{copy('Ouvrir', 'Open')}</Link>}</div>)}{visible.length === 0 && <p className="py-6 text-sm text-neutral-500">{copy('Aucun point pour cette sélection.', 'No items for this selection.')}</p>}</div>
    </>}
  </section>
}
