import { ArrowUpRight, Check } from 'lucide-react'
import { useT } from '../lib/i18n'

const packs = [
  { id: 'launch', initial: 2290, monthly: 249.99, initialSaving: 190, monthlySaving: 0,
    fr: { name: 'Lancement', tagline: 'Une marque. Une présence.', description: 'Les bases pour inspirer confiance et présenter votre activité.', items: ['Identité visuelle & mini-charte', 'Site vitrine · 5 pages, 1 langue', 'Suivi et entretien du site'], scope: 'Branding : 2 pistes, 1 retenue, 2 séries de retours et guide de 10 pages. Site : responsive, formulaire et SEO de base ; contenus fournis par le client, 2 séries de retours.', recurring: 'Entretien du site et vérification du formulaire ; 1 modification de contenu de 30 minutes par mois. L’accompagnement branding mensuel n’est pas inclus.' },
    en: { name: 'Launch', tagline: 'One brand. A real presence.', description: 'The foundations to build trust and showcase your business.', items: ['Visual identity & brand guide', 'Business website · 5 pages, 1 language', 'Website care and monitoring'], scope: 'Branding: 2 concepts, 1 selected, 2 revision rounds and a 10-page guide. Website: responsive, form and basic SEO; client-supplied content, 2 revision rounds.', recurring: 'Website care and form checks; one 30-minute content update per month. Monthly branding support is not included.' } },
  { id: 'acquisition', initial: 1890, monthly: 649.99, initialSaving: 90, monthlySaving: 50,
    fr: { name: 'Acquisition', tagline: 'De la visite au contact.', description: 'Un site et un canal publicitaire pour générer des demandes mesurables.', items: ['Site vitrine · 5 pages, 1 langue', 'Google Ads ou Meta Ads', 'Entretien, optimisation & bilan mensuel'], scope: 'Site identique au pack Lancement, sans branding. Un seul canal choisi au devis : Google Search (2 campagnes, 4 groupes) OU Meta (2 campagnes, 4 ensembles et 4 variations statiques fournies). 1 compte, 1 pays, 1 langue ; budget média jusqu’à 2 000 €/mois, payé séparément.', recurring: 'Suivi web inclus. Optimisation publicitaire hebdomadaire, bilan et point mensuel de 30 minutes. Google : 1 test d’annonce/mois. Meta : 4 variations statiques/mois à partir des contenus fournis.' },
    en: { name: 'Acquisition', tagline: 'From visits to enquiries.', description: 'A website and one advertising channel to generate measurable enquiries.', items: ['Business website · 5 pages, 1 language', 'Google Ads or Meta Ads', 'Care, optimisation & monthly report'], scope: 'Same website as Launch, without branding. One channel selected in the quote: Google Search (2 campaigns, 4 ad groups) OR Meta (2 campaigns, 4 ad sets and 4 supplied static variations). 1 account, 1 country, 1 language; media budget up to €2,000/month, paid separately.', recurring: 'Website care included. Weekly ad optimisation, reporting and a 30-minute monthly review. Google: 1 ad test/month. Meta: 4 static variations/month using supplied content.' } },
  { id: 'growth', initial: 3190, monthly: 849.99, initialSaving: 280, monthlySaving: 99,
    fr: { name: 'Croissance', tagline: 'Attirer. Organiser. Avancer.', description: 'L’acquisition et une automatisation pour mieux traiter les demandes reçues.', items: ['Tout le pack Acquisition', '1 automatisation IA de suivi des leads', 'Surveillance & ajustements du workflow'], scope: 'Périmètre Acquisition, plus 1 workflow : formulaire → CRM → tâche de suivi, par exemple. Maximum 3 connecteurs accessibles et 2 étapes IA. Volumes, exceptions et accès confirmés au devis. Aucun second canal publicitaire ni application sur mesure inclus.', recurring: 'Suivi web et publicitaire du pack Acquisition, plus contrôle des erreurs et jusqu’à 1 heure d’ajustements mineurs du workflow par mois, non reportable. Envois extérieurs et actions sensibles soumis à validation humaine.' },
    en: { name: 'Growth', tagline: 'Attract. Organise. Progress.', description: 'Acquisition with an automation to handle incoming enquiries more effectively.', items: ['Everything in Acquisition', '1 AI lead follow-up workflow', 'Workflow monitoring & adjustments'], scope: 'Acquisition scope plus 1 workflow, e.g. form → CRM → follow-up task. Maximum 3 accessible connectors and 2 AI steps. Volumes, exceptions and access agreed in the quote. No second ad channel or custom application included.', recurring: 'Acquisition website and advertising support, plus error checks and up to 1 hour of minor workflow adjustments per month, with no rollover. External messages and sensitive actions require human approval.' } },
]

export default function OfferPackages() {
  const { locale } = useT()
  const c = (fr: string, en: string) => locale === 'fr' ? fr : en
  const money = (amount: number) => new Intl.NumberFormat(locale === 'fr' ? 'fr-BE' : 'en-GB', { style: 'currency', currency: 'EUR', minimumFractionDigits: Number.isInteger(amount) ? 0 : 2 }).format(amount)
  return <section className="packs-section" aria-labelledby="packs-heading">
    <div className="packs-hero">
      <div className="packs-hero-content">
        <p className="packs-eyebrow">ARQELY · {c('LES PACKS', 'THE PACKAGES')}</p>
        <h2 id="packs-heading">{c('Votre prochain', 'Your next')}<br/><span>{c('mouvement.', 'move.')}</span></h2>
        <p>{c('Des services qui vont ensemble. Un périmètre clair. Un prix fixe.', 'Services that work together. Clear scope. One fixed price.')}</p>
        <a href="#individual-offers" className="packs-link">{c('Explorer les services à la carte', 'Explore individual services')} <ArrowUpRight size={16}/></a>
      </div>
    </div>
    <div className="packs-grid">
      {packs.map((pack, index) => { const text = pack[locale]; return <article key={pack.id} className={`pack-card ${index === 1 ? 'pack-featured' : ''}`}>
        <div className="pack-topline"><span>0{index + 1} / {text.name}</span>{index === 1 && <span className="pack-badge">{c('Acquérir des clients', 'Client acquisition')}</span>}</div>
        <h3>{text.tagline}</h3><p className="pack-description">{text.description}</p>
        <div className="pack-price"><strong>{money(pack.initial)}</strong><span>{c('à la création · HTVA', 'setup · excl. VAT')}</span></div>
        <div className="pack-monthly"><strong>{money(pack.monthly)}</strong><span>{c('/mois HTVA', '/month excl. VAT')}</span></div>
        <ul>{text.items.map(item => <li key={item}><Check size={16} aria-hidden="true"/><span>{item}</span></li>)}</ul>
        <p className="pack-saving">{c('Économie sur les standards à la carte : ', 'Savings against individual standard rates: ')}{money(pack.initialSaving)}{c(' à la création', ' on setup')}{pack.monthlySaving > 0 && <> + {money(pack.monthlySaving)}{c('/mois', '/month')}</>}.</p>
        <details><summary>{c('Ce qui est inclus', 'What is included')}</summary><div className="pack-details"><h4>{c('À la création', 'Setup')}</h4><p>{text.scope}</p><h4>{c('Chaque mois', 'Every month')}</h4><p>{text.recurring}</p></div></details>
      </article>})}
    </div>
    <p className="packs-note">{c('Prix du pack avec les services listés uniquement. Mensuel dès activation des prestations récurrentes ; pour Lancement, entretien après livraison en option. Durée et résiliation précisées au devis. Budgets publicitaires, hébergement, domaines, licences et consommation IA exclus. Les périmètres détaillés des services s’appliquent. Toute demande supplémentaire fait l’objet d’un prix fixe accepté avant réalisation.', 'Package prices cover only the listed services. Monthly billing starts when recurring services activate; Launch website care is optional after delivery. Term and cancellation are specified in the quote. Ad spend, hosting, domains, licences and AI usage are excluded. Detailed service scopes apply. Additional requests require an agreed fixed quote before work starts.')}</p>
    <details className="card p-4 mb-8"><summary className="cursor-pointer text-sm">{c('Repères internes · rentabilité des packs', 'Internal guide · package margins')}</summary><p className="text-sm text-neutral-500 mt-3">{c('Simulation, pas des coûts confirmés : travail valorisé à 50 €/h, provisions directes incluses. Coûts initiaux estimés Lancement / Acquisition / Croissance : 1 300 / 1 040 / 1 840 €, soit environ 43 / 45 / 42 % de marge contributive. Coûts mensuels estimés : 47,50 / 247,50 / 347,50 € (hypothèse Meta, la plus coûteuse). Hors frais généraux, prospection et impôts. Vérifier les heures et coûts réels avant chaque devis ; les gains sont comparés au catalogue standard, pas aux fiches personnalisées ni au marché.', 'Simulation, not confirmed costs: labour valued at €50/h, including direct provisions. Estimated Launch / Acquisition / Growth setup costs: €1,300 / €1,040 / €1,840, giving approximately 43 / 45 / 42% contribution margins. Estimated monthly costs: €47.50 / €247.50 / €347.50 (higher-cost Meta assumption). Before overhead, sales and tax. Check actual hours and costs before quoting; savings compare standard catalogue rates, not custom offers or market prices.')}</p></details>
  </section>
}
