import { useT } from '../lib/i18n'
export default function OfferPolicy() {
 const {locale}=useT();const c=(fr:string,en:string)=>locale==='fr'?fr:en
 return <details className="card p-5 mb-6"><summary className="cursor-pointer font-medium text-sm">{c('Forfaits, suppléments et rentabilité','Fixed packages, extras and profitability')}</summary><div className="space-y-5 text-sm text-neutral-600 mt-5 max-w-4xl">
 <p className="font-medium text-neutral-900">{c('Un prix fixe pour un périmètre défini. Toute demande hors périmètre fait l’objet d’un devis complémentaire accepté avant réalisation.','A fixed price for a defined scope. Every out-of-scope request requires an additional fixed quote approved before work starts.')}</p>
 <ul className="list-disc pl-5 space-y-2"><li>{c('Standard : livrables, volumes, retours, délais et accompagnement précisés au devis.','Standard: deliverables, volumes, revisions, timeline and support specified in the quote.')}</li><li>{c('Complexité connue dès le départ : forfait supérieur chiffré avant signature, sans supplément surprise.','Complexity known upfront: a higher fixed quote before signing, with no surprise extras.')}</li><li>{c('Nouvelle page, fonctionnalité, campagne, langue ou automatisation : prix complémentaire fixe avant réalisation.','New page, feature, campaign, language or workflow: additional fixed price before implementation.')}</li><li>{c('Une sous-estimation interne du travail promis reste à notre charge. Les heures servent à piloter la marge, pas à facturer automatiquement un dépassement au client.','Underestimating promised work is our responsibility. Hours track margin; they do not trigger automatic additional charges.')}</li></ul>
 <p>{c('Publicité, hébergement, domaines, licences et consommation API sont séparés et annoncés au devis. Pas de service illimité ni d’astreinte 24/7. Les contrats existants conservent leurs conditions.','Advertising spend, hosting, domains, licences and API usage are separate and disclosed in the quote. No unlimited service or 24/7 on-call support. Existing contracts retain their terms.')}</p>
 <section><h3 className="font-medium text-neutral-900 mb-2">{c('Repères internes de rentabilité','Internal profitability assumptions')}</h3><p>{c('Hypothèse de calcul : 50 €/h de coût de production, à remplacer par le coût réel de chaque intervenant. Ce n’est ni un tarif facturé ni un salaire net confirmé. Cible proposée : au moins 40 % de marge contributive après temps et frais directs, avant frais fixes, prospection et impôts.','Planning assumption: €50/hour production cost, to be replaced by each contributor’s actual cost. This is neither a billing rate nor confirmed take-home pay. Proposed target: at least 40% contribution margin after labour and direct costs, before overhead, sales and taxes.')}</p><p className="mt-2">{c('Prix minimum interne = (heures prévues × coût horaire + frais directs et provision) ÷ 0,60. Exemple : Google Ads à 450 €/mois, 3 h × 50 € + 25 € de frais = 275 € de contribution (61,1 %). À 6 h, elle tombe à 125 € (27,8 %). Rentabilité à vérifier sur le temps réellement passé.','Internal minimum price = (planned hours × hourly cost + direct costs and contingency) ÷ 0.60. Example: Google Ads at €450/month, 3 h × €50 + €25 costs leaves €275 contribution (61.1%). At 6 h, this falls to €125 (27.8%). Validate profitability against actual hours.')}</p></section>
 <section><h3 className="font-medium text-neutral-900 mb-2">{c('Capacité de l’équipe','Team capacity')}</h3><p>{c('Louka : 10 h/semaine · Alberto : 10 h · Yasin (développement) : 20 h. Total : 40 h/semaine, environ 173 h/mois. Répartir selon les compétences et réserver du temps aux échanges et imprévus. Objectif : 10 000 € de CA mensuel, pas un revenu actuel ni garanti. Le récurrent reste distinct des prestations initiales.','Louka: 10 h/week · Alberto: 10 h · Yasin (development): 20 h. Total: 40 h/week, around 173 h/month. Allocate by skills and allow for communication and unexpected work. Target: €10,000 monthly revenue, not current or guaranteed income. Recurring revenue stays separate from initial services.')}</p></section>
 </div></details>
}
